### ISSUE TITLE
Create index.html

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/kamandprompt.github.io#1]
Create a generic index.html with basic initialisation, along with a navbar having SSH-IITMandi and tabs such as about, projects. 
Make a PR with or without CSS done, only basic HTML setup can also made and then a PR.

**Comment by rishi-s8** [comment]
I'll do it.

**Comment by abhigyank** [comment]
Good. I suggest you get started with the basic HTML structure like including the title, a simple body with a heading. Get going in a different branch. Then we can see how it goes.

**Comment by rishi-s8** [comment]
What should we do next?

**Comment by abhigyank** [comment]
Can you do the styling part now of the top navbar and the footer part?

**Comment by rishi-s8** [comment]
Yes. I would. 
How should the looks be?

**Comment by abhigyank** [comment]
Closed #1 via #2 and #4.
