### ISSUE TITLE
Feature request: Jekyll based feature rich website

### ISSUE THREAD

**Issue by sahilarora535** [KamandPrompt/kamandprompt.github.io#16]
The current stage of website UI is great. However, from what I see, there is no functionality currently on the website. Also, it seems that the website you are aiming at is a single page website and not a blog website. What I would personally prefer is a blog website where people can post blogs, documentation, tutorials, etc. A website from scratch will be a pain for the current and future developers.

For that, it would be great if you build upon an existing template or a framework rather than going from scratch. One of the highly used frameworks is [Jekyll](https://jekyllrb.com/) which is used by many websites, including the website of [Programming Club, IIT Kanpur](http://pclub.in)(the UI in their website is very bad, though the functionality is good).

I recently created my website using [Minimal mistakes jekyll theme](https://github.com/mmistakes/minimal-mistakes/) since it is super customizable and feature rich and it would be great if you have a look at it. Combining your UI with the power of jekyll would make a great website.

**Comment by akshat157** [comment]
This issue has been resolved as a new repository here : https://github.com/KamandPrompt/kamandprompt.github.io.jekyll

Closing!
