### ISSUE TITLE
Fix responsiveness of Home Page

### ISSUE THREAD

**Issue by rishi-s8** [KamandPrompt/kamandprompt.github.io#19]
The Homepage is not completely responsive. The footer height needs to be modified for different screen sizes. The Navigation Bar also doesn't seem quite responsive.

**Comment by rishi-s8** [comment]
The Links in navbar are shifted a bit right, try correcting them for a start.

**Comment by vsvipul** [comment]
will fix this today.. :)

**Comment by rishi-s8** [comment]
@vsvipul What is the Status?

**Comment by vsvipul** [comment]
still working on it, something seems to be not working... need some time..

**Comment by rishi-s8** [comment]
Job done. 👍
