### ISSUE TITLE
Logo of the Programming Club

### ISSUE THREAD

**Issue by rishi-s8** [KamandPrompt/kamandprompt.github.io#20]
The textual logo "KamandPrompt" on the navigation baar looks good, but we need the Programming Club logo like the one attached for the the website. Also check if it can match with the colour scheme, else we need to change that too.
![screen shot 2018-06-15 at 8 54 14 pm](https://user-images.githubusercontent.com/33762894/41476239-96c26c4c-70de-11e8-860a-293beaa4b397.png)

**Comment by abhigyank** [comment]
Where do you plan to add the logo?

**Comment by rishi-s8** [comment]
Top left, for a start. I don't think the text *KamandPrompt* looks very appealing. What do you think?

**Comment by abhigyank** [comment]
Yes, it can go a bit smaller. The logo is black on white though, our website is having a black navbar. I think we'd need to invert the logo?

**Comment by akshat157** [comment]
Don't worry @abhigyank , this is why you have graphic designer in the team. :sunglasses: :stuck_out_tongue:

**Comment by akshat157** [comment]
Issue solved!
