### ISSUE TITLE
Change GSoC page design

### ISSUE THREAD

**Issue by Sylvia23** [KamandPrompt/kamandprompt.github.io#36]
When we click on the `Kamand Prompt` logo in the navbar at the [GSoC Page](https://kamandprompt.github.io/gsoc/), it redirects to a the [same page](https://kamandprompt.github.io/gsoc/index.html), IMO it should redirect to the [main webpage](https://kamandprompt.github.io/).
Thanks!

**Comment by rishi-s8** [comment]
GSoC page hasn't been completely connected to the main website. We'll get on this issue as we start working on it.

**Comment by abhigyank** [comment]
Let's club this under change/improve gsoc page design one issue.

**Comment by rishi-s8** [comment]
We also need to add the navbar and footer to the page.

**Comment by akshat157** [comment]
Everything on the same page, just stacked over one another won't look good. How do you think the GSoC page should be linked to the website?

**Comment by abhigyank** [comment]
@akshat157   it will be separate page as is now, only the logo should be hyperlinked to the main page.

**Comment by Sylvia23** [comment]
@abhigyank is right. We will have separate pages as it is now. We just need to improve the UI and do proper redirections in the page.

**Comment by akshat157** [comment]
Issue isn't solved yet. We'll change the UI and then the issue will be solved.
