### ISSUE TITLE
Link in SNTC Server Project

### ISSUE THREAD

**Issue by Sylvia23** [KamandPrompt/kamandprompt.github.io#37]
Why does the Project `SNTC Server` Github link opens up this [page](https://github.com/KamandPrompt)
IMO the link should be more explanatory and should open up a relevant page wrt the project.

**Comment by abhigyank** [comment]
@Sylvia23 Please comment write up and the link then we can update it accordingly. :)

**Comment by Sylvia23** [comment]
I expect the developers to know what is appropriate and appeals to the user. In first go, I found the content and the link irrelevant. Hence opened the issue.

**Comment by Sylvia23** [comment]
@abhigyank I expect the developers to know what is appropriate and appeals to the user. In first go, I found the content and the link irrelevant. Hence opened the issue. Thanks!

**Comment by abhigyank** [comment]
In this case, I think the coordinators would be able to give a better insight of the content on the website rather than the developers themselves. If you could help them out with this it'd be great!

**Comment by Sylvia23** [comment]
If this is the case, then I think we should contact the contributors of the SNTC Server itself for more insight and a better write-up.

**Comment by aashish-ak** [comment]
There's no link for the SNTC server, it's a work in progress and a great project of the club which deserves a mention on the website, it's not mandatory to put the link, as the project is accesible only to the members working on it, you can remove the link and also close this issue @abhigyank

**Comment by abhigyank** [comment]
Yes, that is true @aashish-ak . In future we could probably link it to the homepage of sntc server once that is designed. For now removing the link would suffice on the KP website. Closing this issue hence.

**Comment by akshat157** [comment]
ye issue to khule se pehle hi band ho gya @Sylvia23  :cry:
