### ISSUE TITLE
Home Page banner design

### ISSUE THREAD

**Issue by hritikgupta** [KamandPrompt/kamandprompt.github.io#46]
This is more of a design issue. The home page's banner look awkwardly empty, with a comparatively small typewriter text. There can either be addition of appropriate elements/svgs or perhaps increase the font size.

**Comment by akshat157** [comment]
You can go ahead and try to add one. :slightly_smiling_face:

**Comment by DinahLin** [comment]
Can I work on this project?

**Comment by abhigyank** [comment]
@DinahLin  Sure! Feel free to.

**Comment by DinahLin** [comment]
> @DinahLin Sure! Feel free to.

Thank you

**Comment by DinahLin** [comment]
I changed the CSS Part for banner. #50

**Comment by abhigyank** [comment]
Some previews with a backgrounds. Thoughts on moving ahead with one of these?
![screenshot from 2019-02-07 11-49-15](https://user-images.githubusercontent.com/20434085/52396481-13807900-2ad8-11e9-8227-ec670e0d63ee.png)

![screenshot from 2019-02-07 12-01-37](https://user-images.githubusercontent.com/20434085/52396577-69edb780-2ad8-11e9-84bc-0cd9fb06d9ff.png)

![screenshot from 2019-02-07 12-06-36](https://user-images.githubusercontent.com/20434085/52396485-17140000-2ad8-11e9-97bd-5e44fe1b293a.png)

**Comment by akshat157** [comment]
Cloud one seems better. The one with a single cloud. :)

**Comment by abhigyank** [comment]
Closed in 7bbae46a2d8ccded9187665fa92dd1aedc2fc1c4
