### ISSUE TITLE
Styling of the scroll down hyperlink

### ISSUE THREAD

**Issue by hritikgupta** [KamandPrompt/kamandprompt.github.io#47]
This is a styling issue. As shown in the image, the link, visited and hover attributes for the hyperlink `Scroll down to know more` should be set to `inherit` or whatever suits the best.
As an addition, I'd suggest a `fa-icon` (for instance, a down arrow) below the hyperlink, to enhance the UI.
![desktop](https://user-images.githubusercontent.com/24262284/46343912-fc7ad780-c65c-11e8-9320-f2478a8212c4.png)

**Comment by abhigyank** [comment]
Closed in #48 .
