### ISSUE TITLE
Add navbar link to blog

### ISSUE THREAD

**Issue by abhigyank** [KamandPrompt/kamandprompt.github.io#53]
Add a navbar link to blog after projects . Its link is https://kamandprompt.github.io/blog.
In the PR  please add  a screenshot after adding.

**Comment by Shrikha1** [comment]
claim issue

**Comment by Shrikha1** [comment]
what else has to done in this issue?

**Comment by Varunvaruns9** [comment]
Hi,
It seems the navbar links overflow at some resolutions. You can fix that.

![screen shot 2018-12-19 at 3 06 07 am](https://user-images.githubusercontent.com/29421208/50184440-23cb7180-033b-11e9-83e0-fc1ee7905c46.png)

**Comment by abhigyank** [comment]
@Varunvaruns9 Yes that can be fixed. Probably shift to a responsive font size then just `px`. Can you create another issue for that?
I am closing this issue in #54.
