### ISSUE TITLE
Hosting the website on SNTC server

### ISSUE THREAD

**Issue by unkemptArc99** [KamandPrompt/kamandprompt.github.io#63]
Currently the website's URL is kamandprompt.github.io, which is OK for the start. But I would like this to become as kamandprompt.iitmandi.ac.in OR pc.iitmandi.ac.in (whatever you guys like). In order to do that, we will need to host this website on our own server, and SNTC server is the best for it. @aashish-ak and Prabhakar know much about the hosting. I would like everyone to work on this starting now, since the site has taken a basic structure.

**Comment by aashish-ak** [comment]
Thanks for bringing this up, we've already started working on this.

**Comment by unkemptArc99** [comment]
It will be also beneficial for you and the juniors that you also start involving them into this initiative.

**Comment by rishi-s8** [comment]
@abhigyank I asked you this. Had any progress?

**Comment by abhigyank** [comment]
Hosted on http://pc.iitmandi.co.in .
