### ISSUE TITLE
Poor styling in project_contributors page

### ISSUE THREAD

**Issue by Manvi07** [KamandPrompt/kamandprompt.github.io#81]
Body size inadequate, scrolls horizontally. Bold blue underline on project links looks a bit messy!

**Comment by akshat157** [comment]
Good find. The page can take some responsiveness fixes for small displays as well!
Headings and image sizes can be reduced to not look huge.

**Comment by akshat157** [comment]
The page can take some responsiveness fixes for small displays as well!
Headings and image sizes can be reduced to not look huge.

**Comment by abhigyank** [comment]
> Body size inadequate, scrolls horizontally. 

Should be quick fix, Can you do it?

> Bold blue underline on project links looks a bit messy!

Feel free to make PR with an alternate look :)

**Comment by rishi-s8** [comment]
@abhigyank, Tag this with **urgent**. Really doesn't look good.

**Comment by abhigyank** [comment]
Yes, its an easy fix too. Can one of you quickly fix this?

**Comment by LalitNM** [comment]
@kpbot claim
