### ISSUE TITLE
Delete currently hosted kamandprompt.github.io

### ISSUE THREAD

**Issue by aashish-ak** [KamandPrompt/kamandprompt.github.io#88]
Delete the website hosted at kamandprompt.github.io and update README.md

**Comment by abhigyank** [comment]
Any reason why we need to delete website hosted at github.io?

**Comment by abhigyank** [comment]
Its redirecting now to pc.iitmandi.co.in which is fine I suppose. Should just update in README.

**Comment by aashish-ak** [comment]
I thought that having a single hosted website would be better that two.

**Comment by abhigyank** [comment]
Fixed in https://github.com/KamandPrompt/kamandprompt.github.io/commit/7a5904ac15568d44704dd14f4d14940d2e1754b6
